# Generated by Django 6.0 on 2025-12-22 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
                ('region', models.CharField(max_length=100, verbose_name='Область')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100, verbose_name='Авиакомпания')),
                ('departure_time', models.DateTimeField(verbose_name='Время вылета')),
                ('arrival_time', models.DateTimeField(verbose_name='Время прилёта')),
                ('status', models.CharField(default='Запланирован', max_length=50, verbose_name='Статус')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='user.city', verbose_name='Город прилёта')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='user.city', verbose_name='Город вылета')),
            ],
        ),
    ]
